services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportal
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: jobportal
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  springboot:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobportal
      SPRING_DATASOURCE_USERNAME: jobportal
      SPRING_DATASOURCE_PASSWORD: jobportal
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
